
home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 0.114.0
    pullPolicy: IfNotPresent
  
  hostNetwork: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # nginx.org/websocket-services: home-assistant
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - 
    tls: []
    #  - secretName: home-assistant-tls
    #    hosts:
    #      - home-assistant.local

  # hostMounts:
  # - name: homeassistant
  #   hostPath: /var/lib/homeassistant

  persistence:
    enabled: true
    hostPath: /var/lib/homeassistant
    accessMode: ReadWriteMany
    size: 5Gi

  # extraVolumes:
  #   - name: homeassistant
  #     hostPath:
  #       path: /var/lib/homeassistant
  #       type: DirectoryOrCreate

  # extraVolumeMounts:
  #   - name: homeassistant
  #     mountPath: /config