---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.153-190.168.1.170
        - name: pihole
          protocol: layer2
          addresses:
            - 192.168.1.152-192.168.1.152
    prometheusRule:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      tolerations:
        - key: "arm"
          operator: "Exists"
    speaker:
      tolerations:
        - key: "arm"
          operator: "Exists"
