---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.11.5
    env:
      TZ: "America/Chicago"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    persistence:
      config:
        enabled: false
    mariadb:
      enabled: false
    postgresql:
      enabled: false
    influxdb:
      enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: hass.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.9.2
        workingDir: "/config"
        args:
          - user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: vscode.${DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
    tolerations:
      - key: "arm"
        operator: "Exists"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    primary:
      tolerations:
        - key: "arm"
          operator: "Exists"
