---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.11.5
    env:
      TZ: "America/Indiana/Knox"
    persistence:
      config:
        enabled: false
    mariadb:
      enabled: false
    postgresql:
      enabled: false
    influxdb:
      enabled: false
    hostNetwork: true
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${METALLBIP}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: assistant.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - assistant.${DOMAIN}
            secretName: tls-home-internal-ca
