---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-self-signed-ca
  namespace: cattle-system
spec:
  secretName: tls-rancher-self-signed-ca
  commonName: rancher.k3s-master.local
  isCA: true
  issuerRef:
    name: self-signed-issuer
