---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      version: 2.4.8
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      interval: 2m
  values:
    hostname: rancher.k3s-master.local
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: nginx
      tls:
        source: rancher
