---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: cattle-system
      interval: 2m
  values:
    replicas: 1
    hostname: k3s-master.local
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: nginx
