---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: ">=2.0.4"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: monitoring.${DOMAIN}
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      path: /
    adminUser:
      user: ${USER}
      password: ${PASSWORD}
