---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .github/lint/.yamllint.yaml
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.0.3
    hooks:
      - id: forbid-secrets
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        args:
          - --config
          - ".github/lint/.markdownlint.yaml"
