---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
      interval: 5m
  values:
    loki:
      replicas: 1
      persistence:
        enabled: false
      
      extraPorts:
      - port: 7956
        protocol: TCP
        name: loki-gossip-ring
        targetPort: 7946
      serviceMonitor:
        enabled: false
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http-metrics"
      livenessProbe:
        initialDelaySeconds: 60
      readinessProbe:
        initialDelaySeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - loki
            topologyKey: "kubernetes.io/hostname"

    promtail:
      enabled: true
      serviceMonitor:
        enabled: false
      logLevel: debug
      snippets:
        addScrapeJobLabel: true
      extraScrapeConfigs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          label_structured_data: true
          labels:
            job: "syslog"
        relabel_configs:
        - source_labels: ['__syslog_connection_ip_address']
          target_label: 'ip_address'
        - source_labels: ['__syslog_message_severity']
          target_label: 'severity'
        - source_labels: ['__syslog_message_facility']
          target_label: 'facility'
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'
        - source_labels: ['__syslog_message_app_name']
          target_label: 'app'
        - source_labels: ['__syslog_message_src']
          target_label: 'source_ip'
        - source_labels: ['__syslog_message_spt']
          target_label: 'source_port'
        - source_labels: ['__syslog_message_dpt']
          target_label: 'destination_port'
        - source_labels: ['__syslog_message_dst']
          target_label: 'destination_ip'
      syslogService:
        enabled: false
        type: LoadBalancer
        port: 1514
        externalIPs:
        - 10.45.10.16
    nodeSelector:
      node-role.kubernetes.io/worker: "true"