---
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADDRESS_POOL: ENC[AES256_GCM,data:pQ1J820VE08MlVJjyyE+LnohABYhdxT6ZJXX,iv:WttLl/bnpkBpht6Rwn6X20z9Jo2+BVUWEREd6DKNxvs=,tag:yXITBYNgwyhVrKk2pyYsKA==,type:str]
    PIHOLE_ADDRESS: ENC[AES256_GCM,data:sCkS8gvBAYT2horI2DQm6BzDPimsVS7Iy8kQ,iv:hObA3NnGaB9B/KdKmXUzK1gTAzd7C8wpcqR/MxNXzYE=,tag:2s/7cRYo9ooy7AyNQWxjuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-10T13:34:42Z"
    mac: ENC[AES256_GCM,data:NFOCIaHAwkKGPhLqiLjQd5VkP/+XlUvlmGMlwHuzrSFn8g/68KQJy6Gm7gTUwuBpw2wxNIGoNhdmYOgCtFuvvM2ofQRfvRj3meWdNk7aqIAd9fuaroxT22geAwHjLr6LDe6/E8ABmYDqIGgMmK9h3PUOWkrfBSS79VSEJ+IolUQ=,iv:bIDuJbkmL1I4eILjgQZU1+br1r01BVotPyB62jad7ow=,tag:IvUUIpCRFRvHwE+Akvz1Dw==,type:str]
    pgp:
        - created_at: "2022-01-10T13:34:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/6k2WizZ/uzAQ//Zmnfm8l2szM1m18j8Z7B9eHuHZ7tz1UEDkZSy++bVQPf
            I54PPowtCPwhm89p6BT62WFvwpBsaatetspXAuV8AJOgAx/Vq3dMcq4PjmUqRe//
            9zq9CIO9Po/+aAIiySO+eqhgri+NaHbRE3QWHFrolwbyE0+28jcgEcAc11M/tVD+
            opChK0rdzf3gD4+M1SFMuD98eKM5RdIt7oaF71z4RdkGSODj2O1bOKYNt65X2Q3i
            Xq5Ileddp1k0nauunC/xwsXBVtfy6R1FRBsqKmhwPb2EYjCXAdS4UVf26YrhfG4q
            ube/LWpWcRxngw+rArOpneYgi7Ts1QGgFRzTuHzZp9eb5QLZKfI7e8iD53Dfg9QI
            vRNit1VFKBBcuz5p2BefMUYnCMaWqYZp2ZAZ1uLsGLUIl+gexVRAlQGfvOPKVr/P
            Sj93eo/YI4UsvQs2P/emIexwXzvyFQIDojGPXq2GjsCEd0p6l7OPRdqfRXQQKLy7
            Mu/lfgeGmf5N+nhKUIeJyVXBZO+kY5xe5S1M3D4xgIHEeqcGz+nBv6HLeMJEivGH
            EY0s01cd54MhtXB8WO1P3VbNjSz9p302M2+OlF3lqdSB2LuMe51aB1p9iy7nqcQI
            fTnYJAZ+qMj1T6OCKB3nfrcQUwT9e+h2iPbPd+wh9RSkPPSTT+kMkyR8DMo2kbPU
            aAEJAhD3S0VbT7MngXjImLpAHvyM6FjesA7FI5ZRx6eBbot0vZS7wjinlZOO2q9f
            SNB2AtPODuqclt4v/KXRaR2eQHYpbBop7ZfpErYjgZrzcHTRjeALf47fOiaNfQkL
            9DmcbVwls/w5
            =s8/a
            -----END PGP MESSAGE-----
          fp: 32C5D3DB1914C04F1F602A7BFA9400787AFB4DD8
        - created_at: "2022-01-10T13:34:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9zy8T/lZ7DzAQ/+Joi121gimkKWlku8yN57RJtlvBa0IOu5w3mItIhD1q+p
            Tan7Je3WZwhBnmg31f9Jx7vMpkMu6zrHNM4ghIrjl9pScWP08GIN4c4wejSBmlVc
            tprCbjfOjmBLvCl7lUOuNXMA9qJ1Rls8aNkeRw/jcYI70Pz9pawcA/s8GVrwDYx3
            KxwUisoFjGWrCjvjHuMEF4MEZp/uFLwgMPrYPLRZ18nAMf2h9CV2I3xb+hENqsHB
            edBhuPMfMX2WpikM7ljtE1gqIYpdj3IcnAsw68Plohvb6B89ct5MOYS5b8pdse5x
            oqzz+QBS43uzMxMGTqlA6qqVfWmLHMAbMQE3A8Ou+wXR/ggdhYa0BSGMyaIES+fd
            1hTThSKywTmQB8qEd5tjFcVQUbEGzADFkOss+Xubw9ivt1F3H4tLimdqqGbTJreK
            iKjUCz2bFcnkpuD3GqkVbgk4dlrAVhy2UZ5HpUAuiDbMuEOfHcfnEEuaB9i7gqwF
            CaWYkmo2r2V1vV2TZxsrUVZM7Zk84RRqF3PeyhjYlhhw3XZnIerekSpcKIMGqFbW
            F2ZM51AFG0KPqCzEOdKzn72m3IcXKinQH8aO8qFMJ0s856+l4WURGDaXfSApmzC4
            tmwciCGwT3CqsJnUW2Bz//t6gFdLQ65Lnmcw+UyfEcIuIYnSV39HpBR/6bSK9VnU
            aAEJAhBNeM575/sVlHuPcCpFtLAvtE0/BHAOx6HywSc5wMuHZkUtxDUNPaKWOpQc
            oD3UISDVblLayQ8Y9yKPu/wmQeh3ZEd/6RwejI30tQoevizljMsi0AoqvOaigSIn
            HBIC1zYidl9K
            =j24G
            -----END PGP MESSAGE-----
          fp: 875EE69937687A19501E4FB7B7DF9ABE0BEB9B18
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
