---
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADDRESS_POOL: ENC[AES256_GCM,data:/iUjBwH3mbJJvxmxhCRR58eSdY3C1o8duEF/,iv:jtOrQK+cZbahwyyM0q0LF6Cu3DIvZtUfHiQa9M06Tco=,tag:OUFIOnBW2rrBckhWyR6qnw==,type:str]
    PIHOLE_ADDRESS: ENC[AES256_GCM,data:/p2KpLpvP/H+bLTHCoviWZSjcDNIrArql35M,iv:kVqqs+0oIkCV5KgSHHle8pIJ4CVVGhlp0rszqdIZcTw=,tag:5h2kHElmByQmkRKQ/qvdJg==,type:str]
    DOMAIN: ENC[AES256_GCM,data:yS5yk4dJzqJj4G1lZLA0vw==,iv:Xk7Lak32dCUbJ31wd0SOK64eJY4TocHQ0GNsoForUKU=,tag:bzsemzKi7jf9G1yniab07Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-10T13:48:16Z"
    mac: ENC[AES256_GCM,data:qMFGX1VRw/8Ug8sc86CeEADJ4JQGSQDKEx1UlWZsI8riD5D//V9DQZiM8I7Hjo1XePzKQJnREWbzACGxoiN5DQ3GfsuZMD+hTbTtwFC2gNFyj0SZu94qnw1GKZpor6n1m1N7yuIlC1is7+WlS/sBl/Yq32fc9e870G+sWQzsMVU=,iv:u+mcVt5CCfJ6E1fO6gvR1iswLsFFgABLsV4DoGR11dM=,tag:GhgoiSWwgIVp+/pmyd1WMQ==,type:str]
    pgp:
        - created_at: "2022-01-10T13:48:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/6k2WizZ/uzAQ//db/c3fonKiv9ch+1fgMlxZzuMKJ5lf2g1l8jNNdQSrpI
            A999mE3V6K9tGFwdZL3KFCOohiLvGvECmTzEtVJLKZ5ghTulXHJBtYZeuGzE553d
            TJe61BPjZ3NZIyxbnEZAOsRfDNuybD8dPTGaQCZLrT4zHmylM+IcmQLXK6j5G+4u
            iezIKUlFTtshM0uhQLGYIlR1Lh09Zd1PE25kMYrHwQBzbrX39rW7pH5GgZwGY9iX
            kdtjoZ9ryp16xOulekkhSSuFWkRZr8JgJyKW5JQmbz9jLER3+0Tkl/4FsfsNO6o8
            THkl2k9JV6zPQuQ/ad0VmItnjtcFw++YK0WlSVuRuWnP9HbGK2cW/qQ0s0ieSd8/
            QyjGfoj64zXYpeUWbol3cyHKmjnhy3MXc/R6yXeutTHLJCPtt8ShfuD/Jq1Cx83t
            SgcaQuBBYNtGZ3JHup+nVHNdo1q8cc1STStRz7t6XFuVzQ35AiGOJXJs/CDXVlZr
            9sdwRn9koY1GmJS+BX+932XiB3UpDUnDmBslSVBCLX90VgfAgh5QnaxI2zESBLEG
            iAOATw5tJW7hLrZBObYZlrjVLaJhwYI5GEW8Qg8opLgvkQXDp/T1+s7zOgKr7NLn
            GH5Estb4JJF/XgppovkKKi0GlhgnEuZnJ3oyqauOmPwkfXhDY2IDgfEoUbrzvRLU
            aAEJAhDe5ZDlADMyuo3Vy0NOi9WUexDIbnAjOsAXrlG7ialT598XK/605686msnA
            yYANNAUCPhZlNOndurslEIgNrV29hglC/mS8XxAqs9/0hlwAsrypBF/qmboNz57B
            kCkku75sJf/3
            =NmU+
            -----END PGP MESSAGE-----
          fp: 32C5D3DB1914C04F1F602A7BFA9400787AFB4DD8
        - created_at: "2022-01-10T13:48:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9zy8T/lZ7DzAQ//YI7wiu7at03CAPRQaFOIbes9BQeyryfi0QU1RlYgCz5i
            iUo9Oa9rlsWC15+xdwvCTXAg8fvoj2EkARR7thfxX3a5aoBkWLYjFLVlqIeJ0svA
            hn/JL2H/q+NLlLTWn7U3AbM12xCSiKgKdlT5+uLSTLpOFfsvE1ffE+5zBgSs9ZZF
            aUhTl3VsEqBGqrA2BB3vpfT6LdDUJzhYOuTHSISqJpgwkq9uTOvygOUAt6YMNIWy
            9GHxPlOsCCjrSG11A4NsHKCUnexa3rKAKF0be/Itu7iL854GqPgBZGXvJSlzAAWw
            /qjG39NNQiZUElS3NJ1jnHS4OYirsILvw/KPs8kgRSRAd6iR4KI6uXIe8+c3S5bF
            IfB+D+R+e5tt7kLetmromXFnA17fc3UHJ9Zl9ggFmMTHDyhvh9UZv71WsK0kcyEF
            vcMe6e8zdBPvxm3VZnXu/Nsp/PU7a+OTOi6WRC+m9+ax/1LLvhMWHrldlZvwVd/d
            sijJTbcuDqfsjoMl+o+av/ppDUalLUwJQ7NbeuQWTph5vqr8FlK9EtE5zotPtaQj
            T3NlTT36XOdPbylEJe1po24hvaThG56qYamHhtNUG1bVEWMCI7QdPFJfpatfTnh0
            h4szJ7C4DpiT68rp6xq6T7JurTgId/hKSdRdgvp9f4+l9htRkkQtus9E9Eu0MhrU
            aAEJAhAgp3I17UDalQafJxyN+UZyrn7vsFHssrBrRBWE5lI40fQIUG6RiMKTQXuX
            PnrK25u+htEbiJ+0pZwP2dw0oueaepeWSISYVRwgUNVK7blW3mdqTNRnFGIRnYy7
            e/GKvrvT3yVi
            =GSRg
            -----END PGP MESSAGE-----
          fp: 875EE69937687A19501E4FB7B7DF9ABE0BEB9B18
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
