apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: externaldns
        namespace: external-dns
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    valuesFrom:
    - kind: Secret
      name: cloudfare-secrets
      valuesKey: api-token
      targetPath: env.CF_API_KEY
    logLevel: debug
    env:
      CF_API_EMAIL: dillan.teagle.va@gmail.com
    cloudflare:
      proxied: true
    policy: sync
    zoneIdFilters: 
    - f63325c249028d7c70fa6fba2f03bf0c
    domainFilters:
    - teaglebuilt.tech
    registry: "txt"
    createSecret: true
    crd:
      create: true
    metrics:
      enabled: false
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi