apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 5.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: Secret
    name: cloudfare-secrets
    valuesKey: api-token
    targetPath: env.CF_API_KEY
  values:
    image:
      registry: k8s.gcr.io
      repository: external-dns/external-dns
      tag: v0.9.0
    logLevel: debug
    provider: cloudflare
    cloudflare:
      proxied: true
    policy: sync
    zoneIdFilters: 
    - f63325c249028d7c70fa6fba2f03bf0c
    domainFilters:
    - teaglebuilt.tech
    registry: "txt"
    createSecret: true
    crd:
      create: true
    metrics:
      enabled: false
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi