apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 5.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: k8s.gcr.io
      repository: external-dns/external-dns
      tag: v0.9.0
    logLevel: debug
    provider: cloudflare
    cloudflare:
      secretName: kubernetes
      email: dillan.teagle.va@gmail.com
      proxied: true
    domainFilters:
      - "teaglebuilt.tech"
    createSecret: true
    crd:
      create: true
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi