apiVersion: v1
kind: Secret
metadata:
    name: cloudfare-secrets
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:IZUFCrr1qhwH0ETy//roo8qgvjVysrhltRZHOAVED1VSfQVjqg==,iv:aPaYMBUXJ2lhnhFjI7X6Hc3EdN0P7MN9ZG8M7R7ntRw=,tag:A9xY3Gmsy7thlv4QFMff3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-28T15:22:47Z"
    mac: ENC[AES256_GCM,data:oqJxTQcG1TPqix0ixKUGBOC+KwhPLG97vRKRBhXm+Ew+1tog+wAsBiMGbxYdO4S2BnZ+TRMDZ5key7NKzAnL9MV9Xm9rmjZ252IitvnPh7FdKQkEHKiofoJz+Ow48yY1wjAFYjT8FZJUwNVdtTsfUj3SZr7ZzOKjcuJIlCDR8TU=,iv:yA248BTewGKJO6V1jq6go+qFff9jY71QHtt5Lj3z35M=,tag:6CVIjuORQshM1r7m3tyMYw==,type:str]
    pgp:
        - created_at: "2021-11-28T15:22:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA29Set7Q2qSOAQv/fTNIRM4qI6YwOH4BrSLOnl/r1OS79muJu4dXpYrDiJoU
            OUet9aMzSi9NQu4v65eZmgzKmgJBwS5Rc2SU3ik9c964/nndbYX1pwp203Qn5kgC
            e7a73vtOA+EdYWEVb/aRMFGY3pakbuxZOY4GdGMTTqodScWHfUlR8Vz4+hMM/JOd
            5R9DqjyHQr3PzXUEvdr7x7jojZTuW8GgErWvS+q2IqBsNUiicTkHv/kthRA9dL4D
            jZxis3hHHcFXvHtNU1+So15gem00WgQMitChTR/bX6nEuWeILE6l1/yE4np7c9vq
            H/vUgjfWMBSw7Vxj9IjcDdC4x8x04GcJ48ILKL2YwPZ2EADf1RLeoIHt+/FRqS/5
            wjM9x/XgMiruioH+4tlPJYWoFdbr6hRHnkDaVFgB4KEf/L5HHSfQHxhEutWloarA
            zmf1S39IqxMTiKLuCeql4SQUNB+AEs30Q482So/x2QisM1DgyvmnShygnFboLHz0
            0EBFkU0Lbs5X9Cv2c1hD1GgBCQIQjE/CTOK2IDFSGPJfiSsJlXqpFr4WBHjA3t3u
            40PtrtfGfvddB+Od3eM5JZmpXUdXa4BOg7Y4d7STXYIelGhGKtDaGS1mZ1Ir1qYP
            Yx9EMyOXuWqL47j5704UEg3X0suu/3lBZQ==
            =iEX4
            -----END PGP MESSAGE-----
          fp: 4448CD686D629F052D5F56D7BAA8F963CB8737E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
