---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.17.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
      interval: 5m
  values:
  grafana.ini:
    server:
      root_url: "https://grafana.${SECRET_DOMAIN}"