apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    DNS_TOKEN: ENC[AES256_GCM,data:5ragF0asL+WATi03RIL/DPldzg1rXeGNZeqDlkHddryCjNHp,iv:ErnlrdzOd52cf3FpL11TumAsTlKYHgcztsOixe7yUeM=,tag:/K8fPSjKJORmZFjZCrhhsw==,type:str]
    EMAIL: ENC[AES256_GCM,data:vphYmXXIuw1OQed3g70S9Sr0R10wKTQk9Ec=,iv:jjrSFn7f02FALuFA0R+m1YTI1w6QAvYweCBHPo9IwYg=,tag:KKZDsHnEIrUsr++wFmCi3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-28T19:31:29Z"
    mac: ENC[AES256_GCM,data:qm/T4J0CE8K6ptGJzt5ZaH4pMCIP4K26wgELO+I5qWK9J02EhPyM1rUuG0/8o8N1KFXje0G9NFnEBvW8wTAq0SsfT5/uE1Qxn8T9sqEJrYyhVnPNqWG+dWbdarucEZ6Tx0OL+QlijBRRveXH76rEQFbSvztsNnattL/+/DGnuCw=,iv:/UBHaaeJi+JFf/ayPKgZhK8Z4ccCQHKy3t8V9RqTS0Q=,tag:tUxsFI8k4toZ8VMQWMivTQ==,type:str]
    pgp:
        - created_at: "2021-12-28T19:31:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA29Set7Q2qSOAQwArjj7/RvMGTdiC5cS8pFgI+KtytAI4l4cmfZpaFCbhETC
            KXSdu2KsohcOIuBbyWBJNKvxq6huljIrt097JEIeWWXGC3vQjiFw0f9XHJZYfILY
            eY5VPnGV/hNNJ9ebWm754gnviadGjyQTxi5Ep76v7j4NdTIDKfDmIRzXA3R9E1Xb
            xPVxIZCuB5m6JehtszAecwMyBi3/6GJqPeLvleP2aPIuCNNzVf0F4koruFerWMaJ
            D6eP8p4aYK5YpgsLVnU9tywOV2+0qG1KJlqQGWdAYdGdvfSMRSypOeQoz0W/Suy1
            Rvf5XW7t/jEThSm9mI6O2H+anv4zUO8e8e4DyEiU/z7FUB+MRRM5bqT+I51ZOR/e
            YZ7+as5BAK37qXeFmYXLfmaXX/6U38krGlNl3zUkhpiZ6TDrzBSySPbgtPeJ1EHc
            m70y2T9slqc/ZILckioSpiAf2Lh6X6zh1ik/NGsxCoqvCv/ebibzlhsnZMd7cWFq
            sBhGotxmJebg8jI36bjs1GgBCQIQ3uGg4XY0EA/OhBXoSBNvGncMQBrdXJsQrO0K
            AH5hvZKIilKULLUdXlhsihdd40pFB7VOueNm/3wWgOGUxq8vH1LD5vJWOSxmbQZr
            +txfoPMKjbnb+SyYc0yXvKxc+G/HlCTBBg==
            =qLVN
            -----END PGP MESSAGE-----
          fp: 4448CD686D629F052D5F56D7BAA8F963CB8737E0
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
