---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
spec:
  releaseName: heimdall
  chart:
    spec:
      chart: heimdall
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/heimdall
      tag: version-2.2.2
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: ${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${DOMAIN}"
            secretName: tls-internal-ca
