---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
spec:
  releaseName: heimdall
  chart:
    spec:
      chart: heimdall
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/heimdall
      tag: version-2.2.2
    env:
      TZ: "America/Chicago"
      PUID: 2316
      PGID: 2316
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: teaglebuilt-ca-issuer
        hosts:
          - host: heimdall.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls-home-internal-ca
            hosts:
              - "heimdall.${DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: configurations
