apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-teaglebuilt-tech
  namespace: global
spec:
  secretName: unifi-teaglebuilt-tech
  dnsNames:
  - unifi.teaglebuilt.tech
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io