---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teaglebuilt-tech
  namespace: cert-manager
spec:
  secretName: teaglebuilt-tech-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: teaglebuilt.tech
  dnsNames:
    - teaglebuilt.tech
    - '*.teaglebuilt.tech'