apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teaglebuilt-tech
  namespace: cert-manager
spec:
  # The secret name where cert-manager
  # should store the signed certificate.
  secretName: teaglebuilt-tech-tls
  dnsNames:
    - teaglebuilt.tech
    - ha.teaglebuilt.tech
    - unifi.teaglebuilt.tech
  # Duration of the certificate.
  duration: 168h
  # Renew a day before the certificate expiration.
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above,
  # which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer