piVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
  namespace: cert-manager
spec:
  signatureType: OriginECC
  auth:
    serviceKeyRef:
      name: cloudflare-api-token-secret
      key: api-token