apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudfare-issuer
    solvers:
      - dns01:
          cloudflare:
            email: ${EMAIL}
            apiTokenSecretRef:
              name: cloudflare
              key: ${CLOUDFARE_TOKEN}