apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    timezone: Europe/Madrid
    controllerService:
      enabled: true
      type: LoadBalancer
    discoveryService:
      enabled: true
      type: LoadBalancer
    guiService:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
      - host: unifi.teaglebuilt.tech
        paths:
        - path: /
          pathType: Prefix
    persistence:
      enabled: true
    speedtestService:
      enabled: true
      type: LoadBalancer
    stunService:
      enabled: true
      type: LoadBalancer
    syslogService:
      enabled: true
      type: LoadBalancer