---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: homeops-webhook
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/built-home/homeops
  ref:
    branch: master
