apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dnsmadeeasy-webhook
spec:
  interval: 5m
  chart:
    spec:
      chart: dnsmadeeasy-webhook
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
  values:
    groupName: acme.teaglebuilt.tech
    image:
      repository: ghcr.io/k8s-at-home/dnsmadeeasy-webhook
      tag: v1.7.0
    cert-manager:
      enabled: false