apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: duckdns
      sourceRef:
        kind: HelmRepository
        name: ebrianne
        namespace: cert-manager
      version: v1.2.3
  interval: 1m
  values:
    logLevel: 2
    duckdns:
      token: ${DNS_TOKEN}
      clusterIssuer:
        staging:
          create: true
        production:
          create: true
        email: ${EMAIL}
