apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: external-names
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifi.teaglebuilt.tech
spec:
  type: ExternalName
  externalName: 10.244.2.11