apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.4.54
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # external-dns.alpha.kubernetes.io/hostname: teaglebuilt.tech
          # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
        - host: unifi.teaglebuilt.tech
          paths:
          - path: /
            pathType: Prefix
        tls:
          - hosts:
            - unifi.teaglebuilt.tech
            secretName: cloudflare-tls