apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: bitnami
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: "=5.1.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: k8s.gcr.io
      repository: external-dns/external-dns
      tag: v0.8.0
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: cloudflare
            value: token
      - name: CF_API_EMAIL
        value: dillan.teagle.va@gmail.com
    domainFilters:
      - "teaglebuilt.tech"
    provider: cloudflare