apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configurations
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
