---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: ops-alerts
  address: https://github.com/built-home/homeops
  secretRef:
    name: slack-url
