---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: ops-alerts
  address: https://hooks.slack.com/services/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
  secretRef:
    name: slack-url
