---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: homecharts
        namespace: flux-system
  interval: 5m
