---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: homecharts
        namespace: flux-system
  interval: 5m
  values:
    serviceWeb:
      loadBalancerIP: "${METALLBIP}"
    serviceTCP:
      type: ClusterIP
    serviceUDP:
      type: ClusterIP
    hostNetwork: true
    privileged: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: self-signed-issuer
      path: /
      hosts:
        - pihole.${DOMAIN}
      tls:
        - secretName: tls-pihole-internal-ca
          hosts:
            - pihole.${DOMAIN}
    nodeSelector:
      - kubernetes.io/hostname: kmaster01