---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${METALLBIP}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: teaglebuilt-ca-issuer
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: "plex.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls-internal-ca
            hosts:
              - "plex.${DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
