---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.23.0
    env:
      DATA_FOLDER: "config"
      DOMAIN: https://vault.${DOMAIN}
      SIGNUPS_ALLOWED: "false"
      TZ: "America/Chicago"
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
    envFrom:
      - secretRef:
          name: vault-secrets
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "teaglebuilt-ca-issuer"
        hosts:
          - host: vault.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - vault.${DOMAIN}
            secretName: "tls-internal-ca"
      admin:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "vault.${DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - "vault.${DOMAIN}"
    # persistence:
    #   config:
    #     enabled: true
    #     existingClaim: vaultwarden-config
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 15m
        memory: 105M
