apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.11.5
    persistence:
      config:
        enabled: true
    mariadb:
      enabled: false
    postgresql:
      enabled: false
    influxdb:
      enabled: false
    hostNetwork: true
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        hosts:
        - host: ha.teaglebuilt.tech
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - ha.teaglebuilt.tech
          secretName: teaglebuilt-tech-tls