apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.11.5
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-pvc
    mariadb:
      enabled: false
    postgresql:
      enabled: false
    influxdb:
      enabled: false

    ingress:
      main:
        enabled: true