apiVersion: v1
kind: Secret
metadata:
  name: actions-runner-controller-auth
  namespace: actions
data:
  github_app_id: ${GITHUB_APP_ID}
  github_app_installation_id: ${GITHUB_INSTALLATION_ID}
  github_app_private_key: ${GITHUB_PRIVATE_KEY}