---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: actions-runner-controller
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    syncPeriod: 5m
    image:
      repository: summerwind/actions-runner-controller
      tag: v0.25.0
    authSecret:
      create: false
      name: actions-runner-controller-auth
    githubWebhookServer:
      enabled: false