---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: actions-runner-controller
      version: v0.14.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions
  values:
    syncPeriod: 5m