apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
data:
  api-key: changeme # has to be BASE64 encoded "echo -n <API_KEY>|base64" should work on MacOS
