apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: homeops
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./kubernetes/infra/dev
  prune: true
  validation: client