---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.20.3
      sourceRef:
        kind: HelmRepository
        name: homecharts
        namespace: flux-system
      interval: 5m
