---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.20.3
      sourceRef:
        kind: HelmRepository
        name: homecharts
        namespace: flux-system
      interval: 5m
  values:
    ingress_route:
      enabled: true
    env:
      GF_SERVER_DOMAIN: k3s-master.local
      GF_SERVER_ROOT_URL: http://k3s-master.local/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: true

    grafana.ini:
      server:
        root_url: http://k3s-master.local/grafana
