apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: origin-ca-issuer
resources:
  - namespace.yaml
  - crd.yaml
  - role.yaml
  - role-binding.yaml
  - sa.yaml
  - deployment.yaml