---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: changedetection-io
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: dgtlmoon/changedetection.io
      tag: "0.39.7"
    env:
      BASE_URL: "https://change-detection.${DOMAIN}"
      WEBDRIVER_URL: http://localhost:4444/wd/hub
      TZ: "America/Chicago"
    service:
      main:
        ports:
          http:
            port: 5000
