apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADDRESS_POOL: ENC[AES256_GCM,data:yfLCDVetV3au4nUb/hcSykCnVugENdoCtg==,iv:3y6rxmgmVO8K/qLOzahzJGB+CE1qdpJ+XWHUwDCjljo=,tag:xLC9vLoYw7JOfLxnXds+lw==,type:str]
    PIHOLE_ADDRESS: ENC[AES256_GCM,data:5xcDLVQNFpmdbhU8w9Y2WdTdqH92CXGuHuVo,iv:UCi5VaxKTW3OC8iLIaVUtREqYepxsmpVYw/aCo+Xfdc=,tag:SPnyK51h+bh9FZMsw0sMnA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:OEhC4gXfsx4o+l3h,iv:Iwebc2udXDIyFGrZGdcoQLOFSB5wKSBI5NUbiI/TRFA=,tag:4yJc9MSv04wtgS7ksrMcnA==,type:str]
    METALLBIP: ENC[AES256_GCM,data:TZSSLxVOCvlAH3Cy,iv:Zs//Y4/Sxx5mvUzGnICZ8FBj12+ygbPsuqFMxWwAMrc=,tag:2/2r6TKOWh0yAJmBXjnJIA==,type:str]
    POD_CIDR: ENC[AES256_GCM,data:qiytNMGh0PDmFbc3,iv:KrnBOnjl9logUeMfRkVSjEhZ3Zubdj0BhFliLKQyxi4=,tag:/G4S7GxPE4BjYTQowHHImQ==,type:str]
    RPI_MASTER_01: ENC[AES256_GCM,data:/00rorXrtF9+H2op,iv:YzWOArXE3HWqgG1r/xSrUgprY32qd3mpWWgzsCAkx7U=,tag:dNyv22qEbR54boWQ1zt2/Q==,type:str]
    RPI_WORKER_01: ENC[AES256_GCM,data:K3XQIRpfzkDn/p+Amw==,iv:0c64OwQC0ey2vSQveDyP7dVOzvQpOZK7AVDXaFWjp/4=,tag:u3cAhyvBgvmzsytjqDcBrw==,type:str]
    RPI_WORKER_02: ENC[AES256_GCM,data:EU33GXRFYf28G/JgnQ==,iv:Ggvc1AZZSY8fY7mlgMD805a7xvWoaOkk8Y/siyFuq+Y=,tag:eiVE1El0YbMOkt+TdWR98w==,type:str]
    GATEWAYIP: ENC[AES256_GCM,data:Ss4XyAhB0080syE=,iv:UtWYneYl0sH9FREAIEC4euEtAECCGvi514X4Kt2C0xc=,tag:boD3Vj8y22fzk+ZAIDqJow==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:t8yvaSaejBV0gBCXsBhIqI/6lIOCcyq9X5Vx3dEiOw9mFuDHicDBjw==,iv:HLwPuPHoFD66ICYnJ4hZOyjkF6vd9LZM4pKny1JyusY=,tag:0o3vC3F9PQn8t197xTGyaQ==,type:str]
    USER: ENC[AES256_GCM,data:yxzWRriSlyM2PL1+,iv:EEH//yrWoCi60+GyU2jR2A6Q1+xRV6l5Jz5QoUtlFDI=,tag:yija4NR6rUHf6wuMrJi2Hg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:7H39+TjKENw=,iv:bJx+Z0e8YJVYe7Z0ZMouVb4TgOO/ukPknuB5V5J3hvE=,tag:jhgnu4MY0ZrrAd2eZjAmiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-30T14:12:05Z"
    mac: ENC[AES256_GCM,data:7v4p2sIJHu/+hEq08bbsy8hIen5DZSCXvNCs7lJ7RqB9z4HXOe/a7AbDgLPD8JPC/6OCExAxzGDgIPZzzx3Ek/tb9Yhi8UJQ1n8jxjDnealQLj0gnpNGwb8X/PItdF6AQItg6LzcWDgjg22CMRWtyfCJDg22941Z+keZCf/8cxc=,iv:DIBOEgOAenrRdkRjlhJUJHdXq4IWW4wdtm7klQsC6Ig=,tag:LOnBqsqJYPFhwKwztzWLqw==,type:str]
    pgp:
        - created_at: "2022-01-30T14:12:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/6k2WizZ/uzAQ//TGFr6Fr8nD6gQt26wWCAf0OBSKha6yA3e3Ov8WQbeG9v
            d98Yk/iNQEKW/EmIHgmVWPOvi35LMqBbPjIxfcTdWX3ZbFMYTx4KgrJTQJN7wxBX
            zTd3R5wl8nurnDggzZjcxxtjXaWBhBNCXQX3rfztZVUHjDxwEGpNIs7g30+H6Bbc
            Iio1/vjv35UmAVM5UDL6n5iRsjjbrOd0OIFbp8jZ+u8xPMvpzY0+x5A2BANTsCQB
            NrwAP9dVjoPFE9y9qlHuiBQSqmB9b1mkRRjC2zd2XGcl8JQZuggXBXPJZEYN7TQT
            hq9QvHfKs8sdPTXIpHEYPmUTUOCOonz7ecAzb0MB05pulfeo+q/6nuPtkyvk8t0R
            2g+Yc+i2jC8zwixU42Do9/fcY3ny+JhvxCkaTp7lEkG52Wu0KXAgZ18U9OwQjW+S
            7pLerEBb4X9bYBagQdAnuNrbRMYsRY0rHIrCV0wK59e93L46iG4BAGcZiKcQvSLC
            Vx8OxBAb7vRx2ov83c8DvIAGYNQxlrcNDmhSPCYLSbsUsXVoJYeaQrgzY5oTPUK6
            MydKpO2WG3vuejU7vyJvMnuJC4R+2x8HkYQjGnKZSHST0nNvneEUddfXlDlOj3pr
            JNSYqbj23EwbiylAb8Dw4k6iRO44YhSZpfAlfJPgibR960jRk738C0gPe3pgfc/U
            aAEJAhD+F5uBaB4xGnVyGZyjcbzjWRHWBCdhpTKmKd//JGexM25U4/TM0EAXjvTH
            Ms4qXzABmR6EyTnqGPaeqQPLmWg7SftLccNfTXJi2gpJFh4iTnXSTWKYMZmkZnBK
            /VwpU4FmMOoB
            =IeIz
            -----END PGP MESSAGE-----
          fp: 32C5D3DB1914C04F1F602A7BFA9400787AFB4DD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
