apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADDRESS_POOL: ENC[AES256_GCM,data:pt1REclgig/KLJfQDD0tB5GcgVHXTWZArcg0,iv:w/ffxEBV8d6ffHevlD7EOyXzVmrVS6skQ5GHLWTuwZE=,tag:eSY8mKF/J2ecXqlvB5qLSg==,type:str]
    PIHOLE_ADDRESS: ENC[AES256_GCM,data:GAslIC1vrLrKh9e4yJs4b6a7gbEi9RsgzfHG,iv:J2OeeUXYZkoJ7k/uA3+MYvUc2AEom/UeoXQMY8QEX9w=,tag:IzzMgCcqMhO1TkEfumZ0JA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:6BfZP0ruufgv6LGu,iv:Kmccnr5S7wrPMrQqjcB9LnsoJh4FD9eISKE/sVrm3FY=,tag:cHYoWyh4G25eeZTbx8rqEQ==,type:str]
    METALLBIP: ENC[AES256_GCM,data:r+PWSbp6BYG21hXL,iv:JwR18r+0dkufIwRvIUPkCPnPnYupJr+zvgXQENOJjPQ=,tag:TT6plog6Bzy+nY7EahFg8g==,type:str]
    POD_CIDR: ENC[AES256_GCM,data:9rTziaYGjSi3gXxD,iv:DWdXx0Xt/lOC5GwT+jFeimdUpOJ/7IWeLG+beHYp9f8=,tag:GlsfSvGrWa8Dgp5AoKtsMQ==,type:str]
    RPI_MASTER_01: ENC[AES256_GCM,data:+B+6pNH7DZK/mzMX,iv:DgR06Z6vAE6vsU2NfW20iWBnJQxVnkF+h4bxmYIBhtk=,tag:H/JWxYugT6YHWv6LCY7YfQ==,type:str]
    RPI_WORKER_01: ENC[AES256_GCM,data:w1e87Dei1kvvBNNOlQ==,iv:ycuYM4aMqlCaw4nX6SbJl4zDi0yYl5xpMAXGUzW0wJE=,tag:yP26um9+tTOsrl6B3CPSUw==,type:str]
    RPI_WORKER_02: ENC[AES256_GCM,data:4YjAcCbzrti/GpxA,iv:09paQll9pzzAQ9qkdD23ew/m0q/INteieQr/8f2Qjhc=,tag:az+3PZcff5kYjOF3CZaTYg==,type:str]
    GATEWAYIP: ENC[AES256_GCM,data:lWpO/U94H7gJkdGxwQ==,iv:HV5H503HNkTcUzt0+URvhtY+zGkhjuK0LxzjzmanbyQ=,tag:e7hVxiKKXLn4VNBRWyYCYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-20T11:45:01Z"
    mac: ENC[AES256_GCM,data:+iNUfepN12NRyYBxaYUSVrWWd5PYCA9PypWhNblKaHCV9wiqFWU/IQZR4fb7JQc0M+mIU+CdoeZHVVjiBf0RVDJJrAc9ShuyxMgSFEk0y69olwLhLLrUfB6Htj8sM0qqbz713ZNmZDpfj8UWtyljtkcIM4Ei4dRwXjhhJ65kbT8=,iv:9KWarxzD3sJSiM0/RR1QfLNqOELNzWJ37cy2bspw1ow=,tag:4ccmdpVNCgfxd5NttpPBBA==,type:str]
    pgp:
        - created_at: "2022-01-20T11:45:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/6k2WizZ/uzARAAllO/NVwHn1VrAMPNkLeUjS+P9S9P+IqE4lxa89tT+4pS
            rti7js/y0qBvQQ53ibDvGcxmz6T9Mo9nmxvEkvebU3YgfEmFLJ3dAbB8b4A3M169
            RMw2VcWxyt83MqzQ7zvZ45bMaWUYepPr6snXN9kDR2v652KxBj8T1yuvfsDXwU0t
            BjmeYVVOFxyKAfcsW685MySZuvRmTLs86uIqhtoh2MtWkDwGsmeYLDPvgIO1aiBw
            FzQLibirUJsjJWWNH7q32CIdbS9KkoqFmdSBIkus3XCTdZXea6d86JDvkJP+bR3w
            spvAjtlFmylQVUCW8PEI8oaBU3gt4RThPYqXs4/72zystiG3H+i4iWE8dN8YGexd
            f1S6xYGeunimB0HPNy5/ZRYa60sHpYQwDEV5iBx9Wd/NPpre7gHem+CoviL6LUzX
            6oRswmpYFpbAEcBvEsEYcCytV1yOTqVRZ1ixEdP8dW1tyKkvibQLFYKKbWP2IW+I
            7vNV3AaGCAb86VsTxOhQ0/8IPHFwQz1uUDqWv71wr8Q9HRQD8aDQrp2Jt9qwS+QL
            3MceWyF+yKrVczXQyeeDYv3h+HYatJnMdXUaJSO4rTtBYW1AvtpsnCqK5DIVaUSO
            n3VqmTxWAY5t6rQ1JAuRQSoerckw7byZP0IBhuhH9P/NkUpfRQR4ei3oGRf/97HU
            aAEJAhBVDwAvFrlzlP497b8YvfdXXXesfp21wU++gbfO4GnVezG8Bksbk8wnsx+3
            fkH6zCETjv4oJJgSHKj0DFAim6KDYIcBmvrIf+AnsMBvnylYH0vQNK+VgXGLxx2V
            Mh08W/n9e9+1
            =ImbO
            -----END PGP MESSAGE-----
          fp: 32C5D3DB1914C04F1F602A7BFA9400787AFB4DD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
