apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ADDRESS_POOL: ENC[AES256_GCM,data:kTpjC+l+srif6fKSzmyN6N9qhTT4dFtWgcb6,iv:dLSDTLteNAQBqURfEKxaDxEdwo7Qwnrv0FyXW131tu4=,tag:q8bBwE7QnVFosd9HOY1uZw==,type:str]
    PIHOLE_ADDRESS: ENC[AES256_GCM,data:rPASShfcTY+OogYtn9Ey1q1KaZPOnOYROJPh,iv:+963R1NddzrEnnWgZon+gzD1+fyFb8FdutS3MWSXK2A=,tag:P8McIU4GKHsLTYgk4ScrhQ==,type:str]
    DOMAIN: ENC[AES256_GCM,data:3uQlM+vERbdQ0oTKUJ6TPQ==,iv:bleBS09EcAl7ZsGpi3uU5zmQnpbrkQIuUDDKFhbQlFU=,tag:oK0dmwzFkNEwjqZTBre0Dw==,type:str]
    METALLBIP: ENC[AES256_GCM,data:lBkMQ+V88T+VqeWJmQ==,iv:NVK03wU7ND5VWcMCAOu/A4qshFGz1+ZhUH/5iXZdzlk=,tag:vX5QplDdXgfUOFoLElL9cA==,type:str]
    POD_CIDR: ENC[AES256_GCM,data:CXRdRCEQ2AkZqYsj,iv:n4IOVPEz84XDa7ZEaHF1RdVLqITzkIAv/JKsLJ3cYKA=,tag:5AgVt9E30yw1/HOqOG8SWA==,type:str]
    RPI_MASTER_01: ENC[AES256_GCM,data:mP5l5/7OdpCETgOPHw==,iv:nvovxr9GGo2Da/hhKHOo6A+cBRZd8e58W+LLGhnbu8g=,tag:G+7BvhopLt+qurjmaAnkrw==,type:str]
    RPI_WORKER_01: ENC[AES256_GCM,data:qPT6DqyTHVkC+phjFw==,iv:SfnyOodF3PWAQPLJOqbys1csXs4CSRMJbMXGVpFu/p8=,tag:KsbtaeM4pa1m+c5oFzyA/g==,type:str]
    GATEWAYIP: ENC[AES256_GCM,data:gTE7A5XVQvm7v5kkyQ==,iv:dCH2Zo3tnCGZUJJofmCS6+3BSrwlOSecd8AWSrym7SE=,tag:l0+MTj86G5boGH3XavIUqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-12T14:33:05Z"
    mac: ENC[AES256_GCM,data:w2eSsUSpToHvgE2medO1U8btwAG461IWtDSJi27s2MhLt6KOajrH89BdbyuGbH5i3igQANW5SiUSdKHHLV7VVAtoK6YEAQj5vo34phAzFm3F2gpSvsXTUq9qeTxGE9HJUQHA+8A5eMzLq8p+5M0O+TGIAgyRlQqz2l/slCvqQ1w=,iv:D2QN0VkqHn6t/nDTaWE3aziCqEcFpixsPP1u22MLd9E=,tag:3bk8/fh/cfL1CUggcEsJzw==,type:str]
    pgp:
        - created_at: "2022-01-12T14:33:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/6k2WizZ/uzAQ/+OKaBLL9inCdDjnw8zv2kw13pG+EkZ9aNMN5mSCS9ph4p
            PwN2xYRulW6SBUR5W6RlNESykh9c4JY7qwuYIdwBhzUcyMcQ7NO9Lv1Eyky9Rvfn
            g12tJFlP73Ranq2PyQ8riuyIoZG1XP5uuspBrIj0xos3KvK+LmVKZfCIuXKaAG/K
            ReaDXz4YkzdugE/dNgBTeck2rJzP0QfzpGWu1FagJq/JIZM+2zb5OtAZ7D2AMuwf
            yXaluuT4bLk3ZClSGQBSeu0dpCGpRK6dtJ36Sbi7xUcX1Ay5LVT5MvYau68V8Szg
            8b+dBEwKlCbrilY3eZanQdF77WU6hScdgVPjiBh33cdkEcSDgXn4uW62KEPTtrKW
            m5am0RhAbSwextt6Wel2aQ8HTNCgFsTgl4P1sT0cz9QxD0krmVTJvsYA0PBTzIkN
            f02lDALSU8nBXLaXovZs7v8qWufrKWrCYELqRu6k73ClVl+ETiAz4ETrgmdmG9le
            h5fRShvMmTh9ee6VNy5HARRfrNZVTj6HVh8BQ4Ub7e7Um557DtPfKyzbeHyAmSWy
            ohqpKyPDS6/zBOMSOSiHWjY5ipydj+O8Ncu3GZ9aqWZndItQldgKJq1Jq8hisVu9
            zSGDE3+hm22GPqXJWgdGFBiIgGSZK/Dhqs0+Ww2P+1z8RatWfzFghiEr0Y64dAfU
            aAEJAhCen+PBSIZjjSaLzVJM97oqdt+rwS8UoUc/O44jpbCMlcwZGI6LgL5/zUvt
            N7Nd6jPXlJdLy23DO+5CiFCMW2Y1/EWP3Y8iHcali0LbDJEEDPIIl+5VX102cwt+
            1QzJmOt87ZSA
            =nJ0s
            -----END PGP MESSAGE-----
          fp: 32C5D3DB1914C04F1F602A7BFA9400787AFB4DD8
        - created_at: "2022-01-12T14:33:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9zy8T/lZ7DzAQ//UEKQnd9MHE04D4yJVbDq+YqNZbaa47qgTWlKZH1gQmoj
            0+8tup5XjxjSyzc4ZalzL8BfNdbJfPsnqbjUp69FRkTd/u3b93sK7ZTzKO47myqc
            Lhsaf1GUXOwKsexhevcdX1FA9XoGTkBdzv4H8aBsDPMPneRftOKax/7HWurqLeZZ
            btctEayzIpMnzRUB2uqSdDjSlqmprSWkK0G7ixOck8OrZD6Fr6S00MMahvSdWne5
            cALb76FyZQObX2bfu6nTJErwErSe5BdMvgt15jJG1plOSYaRXE7rked/kdOHjb/m
            OX4EEldwjSH8OvY/dZURVDWRlkLvHFmR4Xg5/WnxQASERPvvzaWY7EAWyPapK6PC
            Cdmx2so+Us7Cq44/0qeNMkmy/9uzX6gvQPij7ESufowJQWH5wVw0iaN8Li9zpPPI
            //hrPCbTxnEiJ1DuQYg8xFnPwgvf/bNrcdt6jtYHHkFqMlV3Ko+ATm3blfJTxCNE
            /l3nuaWmn6ELXvl7qkDozmYSlRN9kHFqB41mjjqWKWpJ+XGKwF4rGXf2xXLIAo5v
            yepWRSBVjgTP/KWc6Z6yNtGn26Y7822IJxWE6o5W6rQZamaFXYDDBPjJYIJ4L18O
            oQSJ6C9ORNv1hWL2bTaXmk7q+kjOH2nrQgfmyu4KSc9BSTK2THc0Nftw9K874WnU
            aAEJAhAKBDldV4c+RZY/Xrn7Da00Gvl6zLFiOJqoo7Fiy/fQLM8HD7MnrPBWxkfb
            GyJy2sY6slrEH7HLaad/an13sqw3ejcrm67RDznZN6jfGqdyyLC7u1aKr4/Cx575
            DKkwd+Z/MQIA
            =llq0
            -----END PGP MESSAGE-----
          fp: 875EE69937687A19501E4FB7B7DF9ABE0BEB9B18
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
